# Generated by Django 5.2.7 on 2025-11-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote'), (0, 'No Vote')], default=0),
        ),
    ]
